- name: data-enrichment
  image: data-enrichment
  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com
  env_vars:
    - OPENAI_API_KEY

- name: draft-fetcher
  image: draft-fetcher
  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com
  env_vars:
    - MONGO_URI
    - MONGO_DB
    - MONGO_COLLECTION

- name: page-fetcher
  image: page-fetcher
  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com

- name: pageview-fetcher
  image: pageview-fetcher
  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com

- name: matching-service
  image: matching-service
  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com
  resources:
    cpu: 1
    memory: 4Gi
#- name: traffix-exporter
#  image: traffix-exporter
#  service_account: aller-ai-sa@aller-content-tool.iam.gserviceaccount.com
#  env_vars:
#    - ADP_PROJECT_ID
#    - PLATFORM_API_KEY
#    - PLATFORM_TRAFFIC_ENDPOINT
